"""Test the actual C lookup against every known original/ported text, and legacy assets."""
import hashlib,json,struct,subprocess,sys,tempfile
from pathlib import Path
r=Path(__file__).resolve().parents[1];sys.path.insert(0,str(r/'tools'))
import prepare_russian_v177 as ru,prepare_world_v060 as w,prepare_ui_v060 as ui
source=ru.load_translations();assert len(source)==1834
assert all(en.count('\\^')==v.count('\\^')for en,v in source.items())
raw=(r/'assets/russian177.bin').read_bytes();assert raw[:4]==b'NR77';n=struct.unpack_from('<I',raw,4)[0];table={}
for i in range(n):
 k,v,length=struct.unpack_from('<III',raw,8+i*12);key=raw[k:raw.index(b'\0',k)].decode();table[key]=raw[v:v+length].decode()
cases=set(ru.installed_strings());texts=w.read_json(r.parent/'original/data/I18NTexts.json')
for f in sorted((r.parent/'original/data').glob('Map[0-9][0-9][0-9].json')):
 for e in w.read_json(f)['events']:
  if e:
   for pg in e['pages']:
    if w.page_vm_supported(pg):cases.update(ru.vm_strings(w.compile_vm_commands(pg,texts,True)))
# UI key/item strings from the unchanged four-language database format.
with tempfile.TemporaryDirectory()as td:
 td=Path(td);ui.write_ui_database(r.parent/'original',td);b=(td/'ui060.bin').read_bytes()
 _,ni,nl,io,lo,bo=struct.unpack_from('<4sHHIII',b)
 for i in range(nl):
  at=bo+struct.unpack_from('<I',b,lo+i*4)[0];sz=struct.unpack_from('<H',b,at)[0];cases.add(b[at+8:at+8+sz].decode())
 for i in range(ni):
  _,typ,_,off,size=struct.unpack_from('<HBBII',b,io+i*12)
  if size:
   at=bo+off;ll=struct.unpack_from('<8H',b,at);at+=16
   for sz in ll[:2]:
    en=b[at:at+sz].decode();at+=sz
    if not en.startswith('temp'):cases.add(en)
 cases={en for en in cases if ru.norm(en)};assert all(ru.norm(en)in table for en in cases)
 fixture=bytearray()
 for en in sorted(cases):
  a=en.encode();z=table[ru.norm(en)].encode();fixture+=struct.pack('<II',len(a),len(z))+a+z
 (td/'cases.bin').write_bytes(fixture)
 pre='''#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#define ASSET_ROOT "assets/"
static int g_language;
static uint16_t read_u16_le(const uint8_t *b){return b[0]|b[1]<<8;}
static uint32_t read_u32_le(const uint8_t *b){return b[0]|b[1]<<8|b[2]<<16|((uint32_t)b[3]<<24);}
static void *load_whole_file(const char *p,size_t *n){FILE *f=fopen(p,"rb");if(!f)return NULL;fseek(f,0,SEEK_END);*n=ftell(f);rewind(f);void *b=malloc(*n);assert(fread(b,1,*n,f)==*n);fclose(f);return b;}
#include "runtime/russian.inc"
int main(int argc,char **argv){
 assert(init_russian());FILE *f=fopen(argv[1],"rb");assert(f);uint8_t h[8];
 while(fread(h,1,8,f)==8){size_t n=read_u32_le(h),rn=read_u32_le(h+4);char *en=malloc(n+1),*ru=malloc(rn+1);assert(fread(en,1,n,f)==n);en[n]=0;assert(fread(ru,1,rn,f)==rn);ru[rn]=0;
 for(g_language=0;g_language<4;++g_language){const char *p=en;size_t l=n;assert(!russian_lookup(&p,&l));assert(p==en && l==n);assert(vm_text_language(g_language)==g_language);}
 g_language=4;const char *p=en;size_t l=n;assert(russian_lookup(&p,&l));assert(l==rn && !memcmp(p,ru,rn));assert(vm_text_language(4)==0);free(en);free(ru);}
 fclose(f);free(g_russian);return 0;}
'''
 (td/'t.c').write_text(pre);subprocess.run(['cc','-std=c99','-Wall','-Wextra','-I',str(r),str(td/'t.c'),'-o',str(td/'t')],check=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE);subprocess.run([str(td/'t'),str(td/'cases.bin')],cwd=r,check=True)
# Existing pages, scripts, UI and glyphs are not regenerated by this patch.
base=r.parent/'menu176'
def glyphs(path):
 b=path.read_bytes();return {struct.unpack_from('<I',b,i)[0]:b[i:i+8]for i in range(12,len(b),8)}
old=glyphs(base/'assets/font_map.bin');new=glyphs(r/'assets/font_map.bin');assert all(new[k]==v for k,v in old.items())
for page in range(7):assert (r/f'assets/font_page{page}.t8').read_bytes()==(base/f'assets/font_page{page}.t8').read_bytes()
for f in (base/'assets').glob('*_vm.bin'):assert (r/'assets'/f.name).read_bytes()==f.read_bytes()
for v in table.values():
 for c in v:assert c in '\r\n\t' or ord(c)in new,(repr(c),v)
assert table['greenkey']=='Зелёный ключ' and table['redkey']=='Красный ключ'
s=(r/'main.c').read_text();assert 'if (b[4] <= 4)'in s and 'const char *langs[5]'in s
assert '(g_language + (delta > 0 ? 1 : 4)) % 5'in s
print(f'PASS: {len(cases)} actual/original text and UI cases through C lookup; 1,834 translated fragments; all Cyrillic glyphs; four legacy languages/assets unchanged')
